### ISSUE TITLE
Integrate with libratbag

### ISSUE THREAD

**Issue by FranzXaver** [axel-dd/sharkoon-light2-200#1]
Hi Axel, I have a Sharkoon Light² 100 and thanks to your efforts I could switch off the annoying LEDs.
Are you planning on integrating your work with https://github.com/libratbag/libratbag ?

**Comment by axel-dd** [comment]
Hi Franz, sorry I don't have time to continue with this. You are welcome to take my [documentation / reverse engineering ](https://github.com/axel-dd/sharkoon-light2-200/tree/master/reverse_engineering) of the usb protocol and use it.

**Comment by FranzXaver** [comment]
Ok, I will try to do this. libratbag does only support mice with hardware memory, can you tell me if the Sharkoon Light² mice have hardware memory?

**Comment by axel-dd** [comment]
I think so. It has onboard memory where the current configuration is stored.

![image](https://user-images.githubusercontent.com/6698567/130604189-a01fb61f-b09f-448e-aaf0-ba61457d5a69.png)

**Comment by FranzXaver** [comment]
Thanks, I think we can close this issue.
